spring.application.name: cloud-service-demo

server.port: 7100

eureka:
  client:
    service-url:
      defaultZone: http://young:123456@local1:7001/eureka/,http://young:123456@local2:7002/eureka/




